# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-practice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-practice
  template:
    metadata:
      labels:
        app: devops-practice
    spec:
      containers:
      - name: devops-practice
        image: bhaskar13/devops-practice:latest
        ports:
        - containerPort: 3000
