apiVersion: v1
kind: Service
metadata:
  name: devops-practice-service
spec:
  type: NodePort
  selector:
    app: devops-practice
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30030
